export const careers =  [
    {title: 'Accountant', category: 'Accounting and Finance'},
    {title: 'Financial Analyst', category: 'Accounting and Finance'},
    {title: 'Auditor', category: 'Accounting and Finance'},
    {title: 'Tax Advisor', category: 'Accounting and Finance'},
    {title: 'Investment Banker', category: 'Accounting and Finance'},
    {title: 'Doctor', category: 'Healthcare and Medicine'},
    {title: 'Nurse', category: 'Healthcare and Medicine'},
    {title: 'Pharmacist', category: 'Healthcare and Medicine'},
    {title: 'Dentist', category: 'Healthcare and Medicine'},
    {title: 'Physical Therapist', category: 'Healthcare and Medicine'},

    {title: 'Software Developer', category: 'Information Technology'},
    {title: 'IT Support Specialist', category: 'Information Technology'},
    {title: 'Data Scientist', category: 'Information Technology'},
    {title: 'Network Administrator', category: 'Information Technology'},
    {title: 'Cybersecurity Specialist', category: 'Information Technology'},

    {title: 'Mechanical Engineer', category: 'Engineering'},
    {title: 'Civil Engineer', category: 'Engineering'},
    {title: 'Electrical Engineer', category: 'Engineering'},
    {title: 'Chemical Engineer', category: 'Engineering'},
    {title: 'Biomedical Engineer', category: 'Engineering'},

    {title: 'Teacher', category: 'Education'},
    {title: 'School Counselor', category: 'Education'},
    {title: 'Principal', category: 'Education'},
    {title: 'Educational Administrator', category: 'Education'},
    {title: 'Special Education Teacher', category: 'Education'},

    {title: 'Marketing Manager', category: 'Marketing and Sales'},
    {title: 'Sales Representative', category: 'Marketing and Sales'},
    {title: 'Market Research Analyst', category: 'Marketing and Sales'},
    {title: 'Public Relations Specialist', category: 'Marketing and Sales'},
    {title: 'Advertising Manager', category: 'Marketing and Sales'},

    {title: 'HR Manager', category: 'Human Resources'},
    {title: 'Recruiter', category: 'Human Resources'},
    {title: 'Training and Development Specialist', category: 'Human Resources'},
    {title: 'Compensation and Benefits Manager', category: 'Human Resources'},
    {title: 'HR Analyst', category: 'Human Resources'},

    {title: 'Graphic Designer', category: 'Arts and Entertainment'},
    {title: 'Writer', category: 'Arts and Entertainment'},
    {title: 'Actor', category: 'Arts and Entertainment'},
    {title: 'Musician', category: 'Arts and Entertainment'},
    {title: 'Film Director', category: 'Arts and Entertainment'},

    {title: 'Lawyer', category: 'Law and Public Policy'},
    {title: 'Paralegal', category: 'Law and Public Policy'},
    {title: 'Policy Analyst', category: 'Law and Public Policy'},
    {title: 'Judge', category: 'Law and Public Policy'},
    {title: 'Lobbyist', category: 'Law and Public Policy'},

    {title: 'Biologist', category: 'Science and Research'},
    {title: 'Chemist', category: 'Science and Research'},
    {title: 'Physicist', category: 'Science and Research'},
    {title: 'Research Scientist', category: 'Science and Research'},
    {title: 'Environmental Scientist', category: 'Science and Research'},

    {title: 'Business Analyst', category: 'Business and Management'},
    {title: 'Project Manager', category: 'Business and Management'},
    {title: 'Management Consultant', category: 'Business and Management'},
    {title: 'Operations Manager', category: 'Business and Management'},
    {title: 'Entrepreneur', category: 'Business and Management'},

    {title: 'Hotel Manager', category: 'Hospitality and Tourism'},
    {title: 'Travel Agent', category: 'Hospitality and Tourism'},
    {title: 'Event Planner', category: 'Hospitality and Tourism'},
    {title: 'Chef', category: 'Hospitality and Tourism'},
    {title: 'Tour Guide', category: 'Hospitality and Tourism'},

    {title: 'Construction Manager', category: 'Construction and Skilled Trades'},
    {title: 'Electrician', category: 'Construction and Skilled Trades'},
    {title: 'Plumber', category: 'Construction and Skilled Trades'},
    {title: 'Carpenter', category: 'Construction and Skilled Trades'},

    {title: 'Truck Driver', category: 'Transportation and Logistics'},
    {title: 'Logistics Coordinator', category: 'Transportation and Logistics'},
    {title: 'Pilot', category: 'Transportation and Logistics'},
    {title: 'Supply Chain Manager', category: 'Transportation and Logistics'},
    {title: 'Warehouse Manager', category: 'Transportation and Logistics'},

    {title: 'Store Manager', category: 'Retail and Customer Service'},
    {title: 'Retail Sales Associate', category: 'Retail and Customer Service'},
    {title: 'Customer Service Representative', category: 'Retail and Customer Service'},
    {title: 'Merchandiser', category: 'Retail and Customer Service'},
    {title: 'Cashier', category: 'Retail and Customer Service'},
]